name: todoapp-deployment
run-name: ${{ github.actor }} - ${{ github.sha }}

on: 
  push: 
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 coverage
          pip install -r requirements.txt

      - name: Test with Django's built-in test framework / unittest
        run: python manage.py test -v2

      - name: Generate test coverage report
        run: coverage run --source='.' manage.py test -v2

      - name: Expose the test coverage report
        run: coverage report

      - name: Test code style with flake8
        run: flake8 . --exit-zero --show-source --statistics

      - name: Test code complexity
        run: flake8 . --exit-zero --max-complexity=10 --statistics

      - name: Upload Code as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: todoapp-code
          path: ./src
